/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'instrument': ['Instrument Serif', 'serif'],
        'sans': ['DM Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['56px', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'heading-lg': ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'heading-md': ['22px', { lineHeight: '1.3', letterSpacing: '-0.015em', fontWeight: '600' }],
        'heading-sm': ['18px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['17px', { lineHeight: '1.65', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.6', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '1.0', letterSpacing: '0.06em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '1.0', letterSpacing: '0.08em', fontWeight: '500' }],
        'mono': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
      colors: {
        'neutral-0': '#FFFFFF',
        'neutral-50': '#FAFAF9',
        'neutral-100': '#F5F4F2',
        'neutral-200': '#E8E7E4',
        'neutral-300': '#D1CFC9',
        'neutral-400': '#A8A59D',
        'neutral-500': '#757270',
        'neutral-600': '#4A4845',
        'neutral-700': '#2E2C2A',
        'neutral-800': '#1A1917',
        'neutral-900': '#0F0E0D',
        'ink-primary': '#0F0E0D',
        'ink-secondary': '#4A4845',
        'ink-tertiary': '#A8A59D',
        'ink-disabled': '#D1CFC9',
        'status-safe': '#1A7A4A',
        'status-safe-bg': '#E8F5EE',
        'status-warn': '#B45309',
        'status-warn-bg': '#FEF3C7',
        'status-block': '#9B1C1C',
        'status-block-bg': '#FEE2E2',
        'accent': '#0F0E0D',
      },
    },
  },
  plugins: [],
}
