"""
Two ORM tables:

Transaction: every analysis request and its full result. Stores the reasoning
text generated by reasoning_engine.py alongside the numeric score and decision.

ApiSignal: each individual CAMARA API call result, foreign-keyed to Transaction.
Storing signals separately enables per-API analytics (e.g., which API contributes
most to blocked transactions) and supports future ML training data collection.
"""
from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base
import uuid

class Transaction(Base):
    __tablename__ = "transactions"
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    phone_number = Column(String, nullable=False)
    amount_rwf = Column(Float, nullable=False)
    recipient_wallet = Column(String, nullable=False)
    risk_score = Column(Integer, nullable=False)
    decision = Column(String, nullable=False)          # "approve" | "challenge" | "block"
    reasoning_text = Column(String, nullable=True)     # From reasoning_engine.py
    alert_kinyarwanda = Column(String, nullable=True)  # Only for block decisions
    total_response_ms = Column(Integer, nullable=True)
    signals = relationship("ApiSignal", back_populates="transaction")

class ApiSignal(Base):
    __tablename__ = "api_signals"
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    transaction_id = Column(String, ForeignKey("transactions.id"), nullable=False)
    api_name = Column(String, nullable=False)
    raw_response = Column(JSON, nullable=True)
    risk_contribution = Column(Integer, nullable=False)
    response_ms = Column(Integer, nullable=True)
    timed_out = Column(Boolean, default=False)
    error_message = Column(String, nullable=True)
    transaction = relationship("Transaction", back_populates="signals")
