/**
 * Auto-initialize database tables if they don't exist.
 * Runs on server startup to ensure the schema is ready.
 */
module.exports = async (pool) => {
    try {
        console.log('Checking database schema...');

        // Check if profiles table exists
        const check = await pool.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'profiles'
            );
        `);

        if (check.rows[0].exists) {
            console.log('Database schema already exists.');
            return;
        }

        console.log('Initializing database schema...');

        await pool.query(`
            -- Enable UUID extension
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

            -- Profiles Table
            CREATE TABLE IF NOT EXISTS profiles (
                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                handle TEXT NOT NULL UNIQUE,
                email TEXT UNIQUE,
                aura_score INTEGER NOT NULL DEFAULT 0,
                city TEXT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                last_audit_at TIMESTAMP WITH TIME ZONE,
                is_suspended BOOLEAN NOT NULL DEFAULT false,
                suspension_reason TEXT,
                suspended_until TIMESTAMP WITH TIME ZONE
            );

            CREATE INDEX IF NOT EXISTS idx_profiles_handle ON profiles(handle);
            CREATE INDEX IF NOT EXISTS idx_profiles_aura ON profiles(aura_score);
            CREATE INDEX IF NOT EXISTS idx_profiles_city ON profiles(city);

            -- Quests Table
            CREATE TABLE IF NOT EXISTS quests (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                quest_text TEXT NOT NULL,
                active_at TIMESTAMP WITH TIME ZONE NOT NULL,
                expires_at TIMESTAMP WITH TIME ZONE NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_quests_active_at ON quests(active_at);

            -- Signals Table
            CREATE TABLE IF NOT EXISTS signals (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                quest_id BIGINT REFERENCES quests(id) ON DELETE SET NULL,
                video_url TEXT NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                consensus VARCHAR(5) DEFAULT NULL,
                final_aura_delta INTEGER
            );

            CREATE INDEX IF NOT EXISTS idx_signals_user_id ON signals(user_id);
            CREATE INDEX IF NOT EXISTS idx_signals_quest_id ON signals(quest_id);
            CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);

            -- Audits Table
            CREATE TABLE IF NOT EXISTS audits (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                signal_id BIGINT NOT NULL REFERENCES signals(id) ON DELETE CASCADE,
                auditor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                vote VARCHAR(5) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                UNIQUE(signal_id, auditor_id)
            );

            CREATE INDEX IF NOT EXISTS idx_audits_signal_id ON audits(signal_id);
            CREATE INDEX IF NOT EXISTS idx_audits_auditor_id ON audits(auditor_id);

            -- Vouches Table
            CREATE TABLE IF NOT EXISTS vouches (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                referrer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                referred_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            );

            -- Reports Table
            CREATE TABLE IF NOT EXISTS reports (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                reporter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                signal_id BIGINT NOT NULL REFERENCES signals(id) ON DELETE CASCADE,
                reason TEXT NOT NULL,
                description TEXT,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                resolved_at TIMESTAMP WITH TIME ZONE,
                resolved_by UUID REFERENCES profiles(id),
                resolution_note TEXT
            );

            -- Recap Data Table
            CREATE TABLE IF NOT EXISTS recap_data (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                week_start_date DATE NOT NULL,
                data JSONB NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                UNIQUE(user_id, week_start_date)
            );

            -- Scheduler State Table
            CREATE TABLE IF NOT EXISTS scheduler_state (
                id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
                last_quest_release TIMESTAMP WITH TIME ZONE,
                next_quest_time TIMESTAMP WITH TIME ZONE,
                current_quest_id BIGINT
            );

            -- Blocks Table
            CREATE TABLE IF NOT EXISTS blocks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                blocker_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                blocked_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                UNIQUE(blocker_id, blocked_id)
            );

            -- Notification Settings Table
            CREATE TABLE IF NOT EXISTS notification_settings (
                user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
                daily_quest BOOLEAN NOT NULL DEFAULT true,
                audit_reminder BOOLEAN NOT NULL DEFAULT true,
                aura_milestone BOOLEAN NOT NULL DEFAULT true
            );

            -- Aura Log Table
            CREATE TABLE IF NOT EXISTS aura_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                delta INTEGER NOT NULL,
                reason TEXT NOT NULL,
                reference_id BIGINT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            );

            CREATE INDEX IF NOT EXISTS idx_aura_log_user_id ON aura_log(user_id);
            CREATE INDEX IF NOT EXISTS idx_aura_log_created_at ON aura_log(created_at);

            -- Appeals Table
            CREATE TABLE IF NOT EXISTS appeals (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
                reason TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                reviewed_at TIMESTAMP WITH TIME ZONE,
                reviewed_by UUID REFERENCES profiles(id)
            );

            -- Seed a default quest
            INSERT INTO quests (quest_text, active_at, expires_at)
            VALUES (
                'do something that proves you''re not a bot.',
                NOW(),
                NOW() + INTERVAL '24 hours'
            )
            ON CONFLICT DO NOTHING;
        `);

        console.log('Database schema initialized successfully.');
    } catch (err) {
        console.error('Failed to initialize database schema:', err.message);
        // Don't crash the server - routes have their own fallbacks
    }

    // Run migrations on existing tables (safe to run multiple times)
    try {
        // Make quest_id nullable if it isn't already
        await pool.query(`
            ALTER TABLE signals ALTER COLUMN quest_id DROP NOT NULL;
        `);
        // Drop old FK constraint and re-add with ON DELETE SET NULL
        await pool.query(`
            ALTER TABLE signals DROP CONSTRAINT IF EXISTS signals_quest_id_fkey;
            ALTER TABLE signals ADD CONSTRAINT signals_quest_id_fkey
                FOREIGN KEY (quest_id) REFERENCES quests(id) ON DELETE SET NULL;
        `);
        console.log('Migrations applied successfully.');
    } catch (migrationErr) {
        console.warn('Migration note:', migrationErr.message);
    }

    // Create materialized views if they don't exist
    try {
        await pool.query(`
            CREATE MATERIALIZED VIEW IF NOT EXISTS leaderboard_global AS
            SELECT
                handle,
                aura_score AS aura,
                city,
                RANK() OVER (ORDER BY aura_score DESC) AS rank
            FROM profiles
            WHERE is_suspended = false
            ORDER BY aura_score DESC
            LIMIT 100;
        `);

        await pool.query(`
            CREATE MATERIALIZED VIEW IF NOT EXISTS leaderboard_city AS
            SELECT
                handle,
                aura_score AS aura,
                city,
                RANK() OVER (PARTITION BY city ORDER BY aura_score DESC) AS rank
            FROM profiles
            WHERE is_suspended = false AND city IS NOT NULL
            ORDER BY city, aura_score DESC;
        `);

        // Create indexes on the materialized views for fast lookups
        await pool.query('CREATE INDEX IF NOT EXISTS idx_lb_global_rank ON leaderboard_global(rank);').catch(() => { });
        await pool.query('CREATE INDEX IF NOT EXISTS idx_lb_city_city ON leaderboard_city(city);').catch(() => { });

        console.log('Materialized views ready.');
    } catch (mvErr) {
        console.warn('Materialized views note:', mvErr.message);
    }
};
