-- Database Schema for GLITCH
-- Based on specs.json

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enums
CREATE TYPE vote_type AS ENUM ('human', 'slop');
CREATE TYPE report_reason AS ENUM ('harassment', 'dangerous', 'spam', 'other');
CREATE TYPE report_status AS ENUM ('pending', 'resolved', 'dismissed');
CREATE TYPE aura_reason AS ENUM (
    'signal_submission', 
    'audit_correct', 
    'audit_incorrect', 
    'consistency_bonus', 
    'timing_bonus', 
    'accuracy_bonus', 
    'slop_penalty', 
    'report_penalty'
);
CREATE TYPE appeal_status AS ENUM ('pending', 'reviewed', 'rejected', 'accepted');

-- Profiles Table
CREATE TABLE profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), -- In real Supabase, this references auth.users
    handle TEXT NOT NULL UNIQUE CHECK (handle ~ '^[a-z0-9_]{3,16}$'),
    aura_score INTEGER NOT NULL DEFAULT 0,
    city TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_audit_at TIMESTAMP WITH TIME ZONE,
    is_suspended BOOLEAN NOT NULL DEFAULT false,
    suspension_reason TEXT,
    suspended_until TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_profiles_handle ON profiles(handle);
CREATE INDEX idx_profiles_aura ON profiles(aura_score);
CREATE INDEX idx_profiles_city ON profiles(city);

-- Quests Table
CREATE TABLE quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_text TEXT NOT NULL,
    active_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_quests_active_at ON quests(active_at);

-- Signals Table
CREATE TABLE signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    quest_id BIGINT NOT NULL REFERENCES quests(id) ON DELETE CASCADE,
    video_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    consensus vote_type,
    final_aura_delta INTEGER
);

CREATE INDEX idx_signals_user_id ON signals(user_id);
CREATE INDEX idx_signals_quest_id ON signals(quest_id);
CREATE INDEX idx_signals_created_at ON signals(created_at);

-- Audits Table
CREATE TABLE audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT NOT NULL REFERENCES signals(id) ON DELETE CASCADE,
    auditor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    vote vote_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(signal_id, auditor_id)
);

CREATE INDEX idx_audits_signal_id ON audits(signal_id);
CREATE INDEX idx_audits_auditor_id ON audits(auditor_id);

-- Vouches Table
CREATE TABLE vouches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    referred_id UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_vouches_referrer ON vouches(referrer_id);

-- Reports Table
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    signal_id BIGINT NOT NULL REFERENCES signals(id) ON DELETE CASCADE,
    reason report_reason NOT NULL,
    description TEXT,
    status report_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_by UUID REFERENCES profiles(id),
    resolution_note TEXT
);

CREATE INDEX idx_reports_signal ON reports(signal_id);
CREATE INDEX idx_reports_status ON reports(status);

-- Recap Data Table
CREATE TABLE recap_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    week_start_date DATE NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(user_id, week_start_date)
);

-- Scheduler State Table
CREATE TABLE scheduler_state (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    last_quest_release TIMESTAMP WITH TIME ZONE,
    next_quest_time TIMESTAMP WITH TIME ZONE,
    current_quest_id BIGINT REFERENCES quests(id) ON DELETE SET NULL
);

-- Blocks Table
CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    blocked_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(blocker_id, blocked_id)
);

-- Notification Settings Table
CREATE TABLE notification_settings (
    user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    daily_quest BOOLEAN NOT NULL DEFAULT true,
    audit_reminder BOOLEAN NOT NULL DEFAULT true,
    aura_milestone BOOLEAN NOT NULL DEFAULT true
);

-- Aura Log Table
CREATE TABLE aura_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    delta INTEGER NOT NULL,
    reason aura_reason NOT NULL,
    reference_id BIGINT, -- signal_id or audit_id
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_aura_log_user_id ON aura_log(user_id);
CREATE INDEX idx_aura_log_created_at ON aura_log(created_at);

-- Appeals Table
CREATE TABLE appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status appeal_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by UUID REFERENCES profiles(id)
);

CREATE INDEX idx_appeals_user_id ON appeals(user_id);
CREATE INDEX idx_appeals_status ON appeals(status);

-- Add consensus column to signals (nullable until determined)
ALTER TABLE signals ADD COLUMN IF NOT EXISTS consensus VARCHAR(5) DEFAULT NULL;

-- Materialized Views for Leaderboard (refreshed periodically by scheduler)
CREATE MATERIALIZED VIEW IF NOT EXISTS leaderboard_global AS
SELECT
    p.id,
    p.handle,
    p.aura_score,
    ROW_NUMBER() OVER (ORDER BY p.aura_score DESC) AS rank
FROM profiles p
WHERE p.is_suspended = false
ORDER BY p.aura_score DESC
LIMIT 100;

CREATE MATERIALIZED VIEW IF NOT EXISTS leaderboard_city AS
SELECT
    p.id,
    p.handle,
    p.city,
    p.aura_score,
    ROW_NUMBER() OVER (PARTITION BY p.city ORDER BY p.aura_score DESC) AS rank
FROM profiles p
WHERE p.is_suspended = false AND p.city IS NOT NULL
ORDER BY p.city, p.aura_score DESC;

-- Indexes on materialized views
CREATE UNIQUE INDEX IF NOT EXISTS idx_lb_global_id ON leaderboard_global(id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_lb_city_id ON leaderboard_city(id);
CREATE INDEX IF NOT EXISTS idx_lb_city_city ON leaderboard_city(city);
